services:
  frontend:
    build: ./frontend
    ports:
      - "4200:4200" # 4200:80 for Nginx
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

# :-(
#   oracle:
#     container_name: oracle
#     image: container-registry.oracle.com/database/express:latest
#     ports:
#       - "1521:1521"
#     environment:
#       ORACLE_PDB: XEPDB1
#       ORACLE_PWD: oracle # Password for SYS, SYSTEM, and PDBADMIN
#       ORACLE_CHARACTERSET: AL32UTF8
#     volumes:
#       - oracle-data:/opt/oracle/oradata
# 
# volumes:
#   oracle-data:

