services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "4200:4200" # 4200:80 for Nginx
    depends_on:
      - backend
    # volumes:
    #   - ./frontend/src:/app/src
    develop:
      watch:
        - action: rebuild
          path: ./frontend/src
          ignore:
            - node_modules/

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: rebuild
          path: ./backend

  # geode-locator:
  #   container_name: geode-locator
  #   image: apachegeode/geode
  #   ports:
  #     - "10334:10334"
  #   command: gfsh start locator --name=geode-locator --port=10334 --bind-address=0.0.0.0 --hostname-for-clients=geode-locator --J=-Djava.net.preferIPv4Stack=true

  # geode-server:
  #   container_name: geode-server
  #   image: apachegeode/geode
  #   ports:
  #     - "40404:40404"
  #   volumes:
  #     - ./geode/init-geode.sh:/init-geode.sh
  #   environment:
  #     - LOCATORS=geode-locator[10334]
  #   entrypoint: /init-geode.sh
  #   command: gfsh start server --name=geode-server --locators=geode-locator[10334] --server-port=40404 --bind-address=0.0.0.0 --hostname-for-clients=geode-server
  #   depends_on:
  #     - geode-locator
       
# postgres:
#   container_name: postgres
#   image: postgres:alpine
#   ports:
#     - "5432:5432"
#   environment:
#     POSTGRES_DB: mydatabase
#     POSTGRES_USER: user
#     POSTGRES_PASSWORD: password
#   volumes:
#     - postgres-data:/var/lib/postgresql/data

# volumes:
#   postgres-data:

# :-(
#   oracle:
#     container_name: oracle
#     image: container-registry.oracle.com/database/express:latest
#     ports:
#       - "1521:1521"
#     environment:
#       ORACLE_PDB: XEPDB1
#       ORACLE_PWD: oracle # Password for SYS, SYSTEM, and PDBADMIN
#       ORACLE_CHARACTERSET: AL32UTF8
#     volumes:
#       - oracle-data:/opt/oracle/oradata
# 
# volumes:
#   oracle-data:

